apiVersion: v1
kind: Service
metadata:
  labels:
    app: student-deployment
  name: student-deployment
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: student-deployment
  type: NodePort
status:
  loadBalancer: {}
